name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ] # Déclenche la pipeline

jobs:
  deploy-infrastructure:
    runs-on: self-hosted # On appelle ton runner Vagrant
    
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Builder l'image Docker
        run: |
          # build nouvelle version de l'image
          sudo docker build -t hamustra/api-lacets:latest .
          sudo docker save hamustra/api-lacets:latest | sudo k3s ctr images import -

      - name: Déployer sur l'infrastructure Kubernetes
        run: |
          sudo k3s kubectl apply -f api-config.yaml
          sudo k3s kubectl rollout restart deployment/api-server
